# Generated by Django 4.2.1 on 2023-06-01 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.CharField(choices=[('1', 'Boston Scientific (BSCI)'), ('2', 'Abbott (ABBT)'), ('3', 'ev3/Covidien/Medtronic (MTRNC)'), ('4', 'COOK Medical (COOK)'), ('5', 'Terumo (TRMO)'), ('6', 'Coulmed (COULMD)')], max_length=2, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('abbrev', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('reference_id', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('ref_id_expiry_date', models.CharField(max_length=250, unique=True)),
                ('is_purchased', models.BooleanField(default=True)),
                ('quantity_on_hand', models.IntegerField(default=1)),
                ('quantity_on_order', models.IntegerField(default=0)),
                ('last_modified', models.DateField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pydb4.vendor')),
            ],
            options={
                'ordering': ['-name'],
                'indexes': [models.Index(fields=['ref_id_expiry_date', 'name'], name='pydb4_produ_ref_id__928566_idx')],
                'unique_together': {('reference_id', 'expiry_date')},
            },
        ),
    ]
