# Generated by Django 4.2.1 on 2023-06-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydb4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='N/A', max_length=60),
        ),
    ]
