# Generated by Django 4.2.1 on 2023-06-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydb4', '0003_alter_product_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['expiry_date']},
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, default='N/A', max_length=300),
        ),
    ]
