# Generated by Django 4.2.1 on 2023-06-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydb4', '0004_alter_product_options_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='audit_log',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, default='N/A', max_length=300, null=True),
        ),
    ]
