# Generated by Django 4.2.1 on 2023-06-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pydb4', '0006_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='audit_log',
        ),
    ]
