# Generated by Django 4.2.1 on 2023-06-23 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pydb4', '0007_remove_product_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='omni_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
