# Generated by Django 4.2.1 on 2023-06-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydb4', '0008_auditlog_omni_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='employee',
            field=models.PositiveIntegerField(default='1', verbose_name='Employee last edited'),
        ),
    ]
