# Generated by Django 4.2.1 on 2023-06-27 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pydb4', '0009_product_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='omni_employee',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='employee',
            field=models.PositiveIntegerField(default='1', verbose_name='Employee last edited'),
        ),
        migrations.AlterField(
            model_name='product',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
