# Generated by Django 4.2.1 on 2023-06-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pydb4', '0010_remove_auditlog_omni_employee_auditlog_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='employee',
            new_name='omni_employee',
        ),
        migrations.RemoveField(
            model_name='product',
            name='employee',
        ),
    ]
