# Generated by Django 4.2.1 on 2023-06-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pydb4", "0012_product_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="omni_employee",
            field=models.PositiveIntegerField(
                verbose_name="Employee last edited", blank=False, default=1
            ),
        ),
    ]
