# Generated by Django 4.2.1 on 2023-07-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydb4', '0014_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='choice_field',
            field=models.CharField(choices=[('1', 'Add to Inventory'), ('2', 'Delete from Inventory')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
