# Generated by Django 4.2.1 on 2023-07-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pydb4', '0015_procedure_choice_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='choice_field',
        ),
    ]
