# Generated by Django 4.2.1 on 2023-07-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydb4', '0016_remove_procedure_choice_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='products_used',
        ),
        migrations.AddField(
            model_name='procedure',
            name='products_used',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
