# Generated by Django 4.2.1 on 2023-07-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydb4', '0018_procedure_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='products_used',
            field=models.CharField(default='Test, see admin', max_length=300),
        ),
    ]
