# Generated by Django 4.2.1 on 2023-07-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydb4', '0019_alter_procedure_products_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='products_used',
            field=models.CharField(max_length=300),
        ),
    ]
