# Generated by Django 4.2.1 on 2023-07-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydb4', '0020_alter_procedure_products_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['date_performed']},
        ),
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together={('patient', 'date_performed')},
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['patient', 'procedure'], name='pydb4_proce_patient_7b4b59_idx'),
        ),
    ]
