# Generated by Django 4.2.1 on 2023-07-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydb4', '0021_alter_procedure_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.CharField(choices=[('1', 'Boston Scientific (BSCI)'), ('2', 'Abbott (ABBT)'), ('3', 'ev3/Covidien/Medtronic (MTRNC)'), ('4', 'COOK Medical (COOK)'), ('5', 'Terumo (TRMO)'), ('6', 'Coulmed (COULMD)'), ('7', 'Medline (MEDLNE)'), ('8', 'Bard Peripheral Vascular (BARD)')], max_length=2, primary_key=True, serialize=False, unique=True),
        ),
    ]
