# Generated by Django 4.2.1 on 2023-07-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pydb4', '0022_alter_vendor_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('reference_id', 'expiry_date', 'barcode')},
        ),
    ]
