# Generated by Django 4.2.1 on 2023-09-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydb4', '0023_alter_product_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='pydb4_produ_ref_id__928566_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ref_id_expiry_date',
            new_name='ref_id_lot_number_expiry_date',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='lot_number',
            field=models.CharField(blank=True, default='N/A', max_length=300, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('reference_id', 'expiry_date', 'lot_number')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['ref_id_lot_number_expiry_date', 'name'], name='pydb4_produ_ref_id__d9ed8f_idx'),
        ),
    ]
