# Generated by Django 4.2.1 on 2023-09-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pydb4', '0024_remove_product_pydb4_produ_ref_id__928566_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
